# This file creates a service on kubernetes, after the deployment was prepared.
apiVersion: v1
kind: Service
metadata:
  name: dockertest
  labels:
    app: dockertest
spec:
  type: LoadBalancer
  ports:
  - port: 4711
    name: webservice-port
    protocol: TCP
    targetPort: 3000
  - port: 4712
    name: webservice-port-https
    protocol: TCP
    targetPort: 3300
  selector:
    app: dockertest